### ISSUE TITLE
AttributeError flask-login current_user.is_authenticated example 6b

### ISSUE THREAD

**Issue by cdeil** [miguelgrinberg/oreilly-intro-to-flask-video#5]
First: thank you @miguelgrinberg for this wonderful tutorial!

Example 6b doesn't work with the current stable flask-login 0.3.2

Full log: https://gist.github.com/cdeil/bba083e952960f525be0

I think the origin of the issue is a backwards-incompatible change in flask-login 0.3.
See this issue: https://github.com/lingthio/Flask-User/issues/108

**Comment by cdeil** [comment]
See https://github.com/maxcountryman/flask-login/blob/master/CHANGES#L43

**Comment by miguelgrinberg** [comment]
Oh yes, thanks for the reminder, I have updated other projects of mine, but this one slipped.
